//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding.Lizards.Pokemon.Tools.Web.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coding.Lizards.Pokemon.Tools.Web.Strings.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attacken ähnelt.
        /// </summary>
        public static string _Layout_Attacks {
            get {
                return ResourceManager.GetString("_Layout_Attacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;copy; Coding Lizards GbR &amp;mdash; Backgroundpicture &amp;copy; Pokémon &amp;sdot; Nintendo &amp;sdot; Creatures &amp;sdot; GAME FREAK ähnelt.
        /// </summary>
        public static string _Layout_Footer_Copyright {
            get {
                return ResourceManager.GetString("_Layout_Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pokémon ähnelt.
        /// </summary>
        public static string _Layout_Pokemon {
            get {
                return ResourceManager.GetString("_Layout_Pokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pokémon Toolbox ähnelt.
        /// </summary>
        public static string _Layout_Title {
            get {
                return ResourceManager.GetString("_Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzerverwaltung ähnelt.
        /// </summary>
        public static string _Layout_Usermanager {
            get {
                return ResourceManager.GetString("_Layout_Usermanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ändern ähnelt.
        /// </summary>
        public static string _LoginPartial_ChangePassword {
            get {
                return ResourceManager.GetString("_LoginPartial_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo {0}! ähnelt.
        /// </summary>
        public static string _LoginPartial_Greeting {
            get {
                return ResourceManager.GetString("_LoginPartial_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        /// </summary>
        public static string _LoginPartial_Login {
            get {
                return ResourceManager.GetString("_LoginPartial_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abmelden ähnelt.
        /// </summary>
        public static string _LoginPartial_Logoff {
            get {
                return ResourceManager.GetString("_LoginPartial_Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string Account_Login_Email {
            get {
                return ResourceManager.GetString("Account_Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        /// </summary>
        public static string Account_Login_Password {
            get {
                return ResourceManager.GetString("Account_Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        /// </summary>
        public static string Account_Login_Submit {
            get {
                return ResourceManager.GetString("Account_Login_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        /// </summary>
        public static string Account_Login_Title {
            get {
                return ResourceManager.GetString("Account_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort bestätigen ähnelt.
        /// </summary>
        public static string Account_Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_Register_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Kennwort entspricht nicht dem Bestätigungskennwort. ähnelt.
        /// </summary>
        public static string Account_Register_ConfirmPassword_Compare {
            get {
                return ResourceManager.GetString("Account_Register_ConfirmPassword_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string Account_Register_Email {
            get {
                return ResourceManager.GetString("Account_Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        /// </summary>
        public static string Account_Register_Password {
            get {
                return ResourceManager.GetString("Account_Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrieren ähnelt.
        /// </summary>
        public static string Account_Register_Submit {
            get {
                return ResourceManager.GetString("Account_Register_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrieren ähnelt.
        /// </summary>
        public static string Account_Register_Title {
            get {
                return ResourceManager.GetString("Account_Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Käfer ähnelt.
        /// </summary>
        public static string Enums_Type_Bug {
            get {
                return ResourceManager.GetString("Enums_Type_Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlicht ähnelt.
        /// </summary>
        public static string Enums_Type_Dark {
            get {
                return ResourceManager.GetString("Enums_Type_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drache ähnelt.
        /// </summary>
        public static string Enums_Type_Dragon {
            get {
                return ResourceManager.GetString("Enums_Type_Dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elektro ähnelt.
        /// </summary>
        public static string Enums_Type_Electric {
            get {
                return ResourceManager.GetString("Enums_Type_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fee ähnelt.
        /// </summary>
        public static string Enums_Type_Fairy {
            get {
                return ResourceManager.GetString("Enums_Type_Fairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kampf ähnelt.
        /// </summary>
        public static string Enums_Type_Fighting {
            get {
                return ResourceManager.GetString("Enums_Type_Fighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feuer ähnelt.
        /// </summary>
        public static string Enums_Type_Fire {
            get {
                return ResourceManager.GetString("Enums_Type_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flug ähnelt.
        /// </summary>
        public static string Enums_Type_Flying {
            get {
                return ResourceManager.GetString("Enums_Type_Flying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geist ähnelt.
        /// </summary>
        public static string Enums_Type_Ghost {
            get {
                return ResourceManager.GetString("Enums_Type_Ghost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pflanze ähnelt.
        /// </summary>
        public static string Enums_Type_Grass {
            get {
                return ResourceManager.GetString("Enums_Type_Grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boden ähnelt.
        /// </summary>
        public static string Enums_Type_Ground {
            get {
                return ResourceManager.GetString("Enums_Type_Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eis ähnelt.
        /// </summary>
        public static string Enums_Type_Ice {
            get {
                return ResourceManager.GetString("Enums_Type_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        /// </summary>
        public static string Enums_Type_Normal {
            get {
                return ResourceManager.GetString("Enums_Type_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gift ähnelt.
        /// </summary>
        public static string Enums_Type_Poison {
            get {
                return ResourceManager.GetString("Enums_Type_Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Psycho ähnelt.
        /// </summary>
        public static string Enums_Type_Psychic {
            get {
                return ResourceManager.GetString("Enums_Type_Psychic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gestein ähnelt.
        /// </summary>
        public static string Enums_Type_Rock {
            get {
                return ResourceManager.GetString("Enums_Type_Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stahl ähnelt.
        /// </summary>
        public static string Enums_Type_Steel {
            get {
                return ResourceManager.GetString("Enums_Type_Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wasser ähnelt.
        /// </summary>
        public static string Enums_Type_Water {
            get {
                return ResourceManager.GetString("Enums_Type_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oder ähnelt.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string User_Add_Cancel {
            get {
                return ResourceManager.GetString("User_Add_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        public static string User_Add_Submit {
            get {
                return ResourceManager.GetString("User_Add_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        public static string User_Add_Title {
            get {
                return ResourceManager.GetString("User_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string User_Delete_Cancel {
            get {
                return ResourceManager.GetString("User_Delete_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll der Benutzer mit der Emailadresse {0} wirklich gelöscht werden? ähnelt.
        /// </summary>
        public static string User_Delete_Content {
            get {
                return ResourceManager.GetString("User_Delete_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string User_Delete_Submit {
            get {
                return ResourceManager.GetString("User_Delete_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string User_Delete_Title {
            get {
                return ResourceManager.GetString("User_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string User_Details_Delete {
            get {
                return ResourceManager.GetString("User_Details_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        public static string User_Details_Edit {
            get {
                return ResourceManager.GetString("User_Details_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string User_Details_Title {
            get {
                return ResourceManager.GetString("User_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string User_Edit_Cancel {
            get {
                return ResourceManager.GetString("User_Edit_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string User_Edit_Submit {
            get {
                return ResourceManager.GetString("User_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        public static string User_Edit_Title {
            get {
                return ResourceManager.GetString("User_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktionen ähnelt.
        /// </summary>
        public static string User_List_Actions {
            get {
                return ResourceManager.GetString("User_List_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        public static string User_List_Add {
            get {
                return ResourceManager.GetString("User_List_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string User_List_Delete {
            get {
                return ResourceManager.GetString("User_List_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        public static string User_List_Edit {
            get {
                return ResourceManager.GetString("User_List_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string User_List_Email {
            get {
                return ResourceManager.GetString("User_List_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        /// </summary>
        public static string User_List_Password {
            get {
                return ResourceManager.GetString("User_List_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzerverwaltung ähnelt.
        /// </summary>
        public static string User_List_Title {
            get {
                return ResourceManager.GetString("User_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername ähnelt.
        /// </summary>
        public static string User_List_Username {
            get {
                return ResourceManager.GetString("User_List_Username", resourceCulture);
            }
        }
    }
}
